development:
  adapter: mysql2
  reconnect: false
  #socket: /tmp/mysql.sock
  database: xlearning
  pool: 5
  username: usuario
  password: "123456"
  host: localhost

production:
  adapter: mysql2
  reconnect: false
  #socket: /tmp/mysql.sock
  database: xlearning
  pool: 5
  username: usuario
  password: "123456"
  host: localhost

test:
  adapter: mysql2
  reconnect: false
  #socket: /tmp/mysql.sock
  database: xlearning
  pool: 5
  username: usuario
  password: "123456"
  host: localhost